# Generated by Django 2.1.7 on 2019-06-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwMapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laninter',
            name='wanip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fwMapping.Waninter'),
        ),
    ]
