# Generated by Django 2.1.7 on 2019-06-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fwMapping', '0002_auto_20190604_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laninter',
            name='wanip',
        ),
        migrations.AddField(
            model_name='mapping',
            name='wanip',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fwMapping.Waninter'),
            preserve_default=False,
        ),
    ]
